/*
nome utente : nerdbook
password: nerdbook
*/

CREATE TABLE postType (
	postType_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(32)
);

CREATE TABLE nerds (
	nerd_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(256) UNIQUE,
	nome VARCHAR(256),
	cognome VARCHAR(256),
	urlFotoProfilo VARCHAR(256),
	frasePresentazione VARCHAR(1024),
	dataNascita VARCHAR(256),
	password VARCHAR(256) NOT NULL,
	email VARCHAR(256),
        usertype BOOLEAN

);

CREATE TABLE posts (
	post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content VARCHAR(1024),
	type INTEGER,	
	author INTEGER,
	FOREIGN KEY (type) REFERENCES postType(posttype_id),
	FOREIGN KEY (author) REFERENCES nerds(nerd_id)
);

CREATE TABLE amicizie (
	follower INTEGER,
	followed INTEGER,
	FOREIGN KEY (follower) REFERENCES nerds(nerd_id),
	FOREIGN KEY (followed) REFERENCES nerds(nerd_id),
	PRIMARY KEY (follower, followed)
);

CREATE TABLE groups (
	group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        creatore INTEGER,
        nome VARCHAR(256),
	urlimmagine VARCHAR(256),
	FOREIGN KEY (creatore) REFERENCES nerds(nerd_id)
);

CREATE TABLE groups_relations (
	gruppo INTEGER,
	utente INTEGER,
	FOREIGN KEY (gruppo) REFERENCES groups(group_id),
	FOREIGN KEY (utente) REFERENCES nerds(nerd_id),
	PRIMARY KEY (gruppo, utente)
);


INSERT INTO nerds (nerd_id, nome, cognome, email, urlFotoProfilo, frasePresentazione, dataNascita, username, password, usertype)
VALUES (default, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', '123', 'true');

INSERT INTO nerds (nerd_id, nome, cognome, email, urlFotoProfilo, frasePresentazione, dataNascita, username, password, usertype)
VALUES (default, 'Steve', 'Jobs', 'steve@apple.com', 'immagini/steve_jobs.jpg', 'Ciao IO sono STEVE!', '02-02-55', 'stevej', '123', 'false');

INSERT INTO nerds (nerd_id, nome, cognome, email, urlFotoProfilo, frasePresentazione, dataNascita, username, password, usertype)
VALUES (default, 'Bill', 'Gates', 'bill@microsoft.com', 'immagini/bill_gates.jpg', 'Io sono Negan', '12-12-55', 'billg', '123', 'false' );

INSERT INTO nerds (nerd_id, nome, cognome, email, urlFotoProfilo, frasePresentazione, dataNascita, username, password, usertype)
VALUES (default, 'Linus', 'Torvalds', 'linus@linux.org', 'immagini/linus.jpg', 'Ciao io sono Linus', '13-04-67', 'linux', '123', 'false');

INSERT INTO nerds (nerd_id, nome, cognome, email, urlFotoProfilo, frasePresentazione, dataNascita, username, password, usertype)
VALUES (default, 'Steven', 'Urkel', 'steven@urkel.bah', 'immagini/steven.jpg', 'Ciao io sono Steven', '27-11-76', 'urkel', '123', 'false');


INSERT INTO groups (group_id, nome, creatore, urlimmagine)
VALUES (default, 'Mongolfieristi', 2, 'img/mongolfiera.jpg');
INSERT INTO groups (group_id, nome, creatore, urlimmagine)
VALUES (default, 'Ritardatari', 3, 'img/sveglia.jpg');
INSERT INTO groups (group_id, nome, creatore, urlimmagine)
VALUES (default, 'Simpaticoni', 2, 'img/simpaticone.jpg');
INSERT INTO groups (group_id, nome, creatore, urlimmagine)
VALUES (default, 'Supercazzolari', 4, 'img/Supercazzolari.jpg');

INSERT INTO amicizie (follower, followed)
VALUES (1,2),(1,3),(2,3),(2,4);

INSERT INTO groups_relations (utenti, gruppi)
VALUES (2,1),(2,3),(3,3),(3,4),(4,1),(4,4);

INSERT INTO posttype (posttype_id, nome)
VALUES  (1, 'testo'),
        (2, 'immagine'),
        (3, 'url');


INSERT INTO posts (post_id, content, type, author)
VALUES (default, 'Questo è il primo messaggio in bacheca', 1, 1);
INSERT INTO posts (post_id, content, type, author)
VALUES (default, 'http://cc-media-foxit.fichub.com/image/floptv/276a97a2-3f7e-4ae9-8ff9-3b0d1546ffc9/immagini-avatar-whatsapp-17-maxw-600.jpg', 2, 2);
INSERT INTO posts (post_id, content, type, author)
VALUES (default, 'Questo è il terzo messaggio in bacheca', 1, 1);
INSERT INTO posts (post_id, content, type, author)
VALUES (default, 'http://cc-media-foxit.fichub.com/image/floptv/1d80f814-eb90-4d4f-b18e-78a601c8d6dd/immagini-avatar-whatsapp-23-maxw-600.jpg', 2, 3);
INSERT INTO posts (post_id, content, type, author)
VALUES (default, 'Questo è il quinto messaggio in bacheca', 1, 3);
INSERT INTO posts (post_id, content, type, author)
VALUES (default, 'Questo è il sesto messaggio in bacheca', 1, 4);


        